apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-api
  labels:
    app: feed-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed-api
  template:
    metadata:
      labels:
        app: feed-api
    spec:
      containers:
        - name: udagram-feed-api
          image: ovidb/udagram-feed-api
          ports:
            - containerPort: 8080
